# Generated by Django 4.0.5 on 2022-07-02 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_rc', '0002_country_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_products', models.CharField(max_length=300)),
                ('condition_products', models.CharField(max_length=50)),
                ('status_products', models.CharField(max_length=30)),
                ('pictures_products', models.ImageField(upload_to='products_pic')),
                ('price', models.DecimalField(decimal_places=5, max_digits=6)),
                ('description_products', models.TextField(max_length=1000)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='site_rc.category')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='site_rc.users')),
            ],
        ),
    ]
