# Generated by Django 4.0.5 on 2022-07-03 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_rc', '0004_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='site_rc.category')),
            ],
        ),
    ]
