# Generated by Django 4.0.5 on 2022-07-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_rc', '0006_alter_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='podcat_id',
            field=models.IntegerField(null=True),
        ),
    ]
