# Generated by Django 4.0.5 on 2022-07-03 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_rc', '0007_products_podcat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcategory',
            name='cat_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='site_rc.category'),
        ),
    ]
